<?php

namespace UserBundle\Repository;

/**
 * NovedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NovedadRepository extends \Doctrine\ORM\EntityRepository
{
}
